services:
  - type: web
    name: helpdesk-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python -c "from fastembed import TextEmbedding; TextEmbedding('BAAI/bge-small-en-v1.5')"
    startCommand: gunicorn -w 1 -k gthread --threads 2 --timeout 180 --graceful-timeout 180 --keep-alive 5 --max-requests 50 --max-requests-jitter 20 --preload app:app
    envVars:
      - key: KNOWLEDGE_BASE_PATH
        value: dataset.csv
      - key: CORS_ORIGINS
        value: "*"




